/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as PublicLoginImport } from './routes/_public/login';
import { Route as AuthHomeImport } from './routes/_auth/home';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute
} as any);

const PublicLoginRoute = PublicLoginImport.update({
  id: '/_public/login',
  path: '/login',
  getParentRoute: () => rootRoute
} as any);

const AuthHomeRoute = AuthHomeImport.update({
  id: '/_auth/home',
  path: '/home',
  getParentRoute: () => rootRoute
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_auth/home': {
      id: '/_auth/home';
      path: '/home';
      fullPath: '/home';
      preLoaderRoute: typeof AuthHomeImport;
      parentRoute: typeof rootRoute;
    };
    '/_public/login': {
      id: '/_public/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof PublicLoginImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/home': typeof AuthHomeRoute;
  '/login': typeof PublicLoginRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/home': typeof AuthHomeRoute;
  '/login': typeof PublicLoginRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/_auth/home': typeof AuthHomeRoute;
  '/_public/login': typeof PublicLoginRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/home' | '/login';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/home' | '/login';
  id: '__root__' | '/' | '/_auth/home' | '/_public/login';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthHomeRoute: typeof AuthHomeRoute;
  PublicLoginRoute: typeof PublicLoginRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthHomeRoute: AuthHomeRoute,
  PublicLoginRoute: PublicLoginRoute
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth/home",
        "/_public/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth/home": {
      "filePath": "_auth/home.tsx"
    },
    "/_public/login": {
      "filePath": "_public/login.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
