/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as WatchvideoImport } from './routes/watch_video';
import { Route as PresentationImport } from './routes/presentation';
import { Route as JoinImport } from './routes/join';
import { Route as DiscussionImport } from './routes/discussion';
import { Route as CreateImport } from './routes/create';
import { Route as IndexImport } from './routes/index';
import { Route as PublicLoginImport } from './routes/_public/login';
import { Route as AuthHomeImport } from './routes/_auth/home';

// Create/Update Routes

const WatchvideoRoute = WatchvideoImport.update({
  id: '/watch_video',
  path: '/watch_video',
  getParentRoute: () => rootRoute
} as any);

const PresentationRoute = PresentationImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRoute
} as any);

const JoinRoute = JoinImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRoute
} as any);

const DiscussionRoute = DiscussionImport.update({
  id: '/discussion',
  path: '/discussion',
  getParentRoute: () => rootRoute
} as any);

const CreateRoute = CreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRoute
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute
} as any);

const PublicLoginRoute = PublicLoginImport.update({
  id: '/_public/login',
  path: '/login',
  getParentRoute: () => rootRoute
} as any);

const AuthHomeRoute = AuthHomeImport.update({
  id: '/_auth/home',
  path: '/home',
  getParentRoute: () => rootRoute
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/create': {
      id: '/create';
      path: '/create';
      fullPath: '/create';
      preLoaderRoute: typeof CreateImport;
      parentRoute: typeof rootRoute;
    };
    '/discussion': {
      id: '/discussion';
      path: '/discussion';
      fullPath: '/discussion';
      preLoaderRoute: typeof DiscussionImport;
      parentRoute: typeof rootRoute;
    };
    '/join': {
      id: '/join';
      path: '/join';
      fullPath: '/join';
      preLoaderRoute: typeof JoinImport;
      parentRoute: typeof rootRoute;
    };
    '/presentation': {
      id: '/presentation';
      path: '/presentation';
      fullPath: '/presentation';
      preLoaderRoute: typeof PresentationImport;
      parentRoute: typeof rootRoute;
    };
    '/watch_video': {
      id: '/watch_video';
      path: '/watch_video';
      fullPath: '/watch_video';
      preLoaderRoute: typeof WatchvideoImport;
      parentRoute: typeof rootRoute;
    };
    '/_auth/home': {
      id: '/_auth/home';
      path: '/home';
      fullPath: '/home';
      preLoaderRoute: typeof AuthHomeImport;
      parentRoute: typeof rootRoute;
    };
    '/_public/login': {
      id: '/_public/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof PublicLoginImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/create': typeof CreateRoute;
  '/discussion': typeof DiscussionRoute;
  '/join': typeof JoinRoute;
  '/presentation': typeof PresentationRoute;
  '/watch_video': typeof WatchvideoRoute;
  '/home': typeof AuthHomeRoute;
  '/login': typeof PublicLoginRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/create': typeof CreateRoute;
  '/discussion': typeof DiscussionRoute;
  '/join': typeof JoinRoute;
  '/presentation': typeof PresentationRoute;
  '/watch_video': typeof WatchvideoRoute;
  '/home': typeof AuthHomeRoute;
  '/login': typeof PublicLoginRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/create': typeof CreateRoute;
  '/discussion': typeof DiscussionRoute;
  '/join': typeof JoinRoute;
  '/presentation': typeof PresentationRoute;
  '/watch_video': typeof WatchvideoRoute;
  '/_auth/home': typeof AuthHomeRoute;
  '/_public/login': typeof PublicLoginRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/create'
    | '/discussion'
    | '/join'
    | '/presentation'
    | '/watch_video'
    | '/home'
    | '/login';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/create'
    | '/discussion'
    | '/join'
    | '/presentation'
    | '/watch_video'
    | '/home'
    | '/login';
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/discussion'
    | '/join'
    | '/presentation'
    | '/watch_video'
    | '/_auth/home'
    | '/_public/login';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CreateRoute: typeof CreateRoute;
  DiscussionRoute: typeof DiscussionRoute;
  JoinRoute: typeof JoinRoute;
  PresentationRoute: typeof PresentationRoute;
  WatchvideoRoute: typeof WatchvideoRoute;
  AuthHomeRoute: typeof AuthHomeRoute;
  PublicLoginRoute: typeof PublicLoginRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  DiscussionRoute: DiscussionRoute,
  JoinRoute: JoinRoute,
  PresentationRoute: PresentationRoute,
  WatchvideoRoute: WatchvideoRoute,
  AuthHomeRoute: AuthHomeRoute,
  PublicLoginRoute: PublicLoginRoute
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create",
        "/discussion",
        "/join",
        "/presentation",
        "/watch_video",
        "/_auth/home",
        "/_public/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create": {
      "filePath": "create.tsx"
    },
    "/discussion": {
      "filePath": "discussion.tsx"
    },
    "/join": {
      "filePath": "join.tsx"
    },
    "/presentation": {
      "filePath": "presentation.tsx"
    },
    "/watch_video": {
      "filePath": "watch_video.tsx"
    },
    "/_auth/home": {
      "filePath": "_auth/home.tsx"
    },
    "/_public/login": {
      "filePath": "_public/login.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
