name: Setup Environment
description: Setup for test & build
inputs:
  token:
    description: 'Personal Access Token'
    required: false
  package:
    description: 'package'
    required: false
runs:
  using: composite
  steps:
    - name: Setup Node
      id: setup_node
      uses: actions/setup-node@v3
      with:
        node-version: 22.13.0

    - uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Install dependencies
      env:
        NPM_TOKEN: ${{ inputs.token }}
      run: |
        if [ -z "${{ inputs.package }}" ]; then
          pnpm i --frozen-lockfile
        else
          pnpm i --frozen-lockfile --filter ${{ inputs.package }}
        fi
      shell: bash
